javascripts:
  pack:
    - public/javascripts/a.js
    - public/javascripts/b.js
    - public/javascripts/c/**/*.js

stylesheets:
  pack:
    - public/stylesheets/a.css
    - public/stylesheets/b.css
